name: CI Pipeline

on:
  push:
    branches:
      - main # Also trigger on commits to the main branch

  pull_request:
    branches:
      - dev
      - main # Also trigger on pull requests to the main branch

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
  k8s-manifest-files_update:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' # Only run this job if the branch is 'main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

          
      
            
