name: k8s Pipeline

on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/go-k8s.yml"
      - "node-test/**"
  pull_request:
    branches:
      - dev
    paths:
      - ".github/workflows/go-k8s.yml"
      - "node-test/**"

jobs:
  k8s-manifest-files_update:
    runs-on: ubuntu-latest
    # if: github.ref == 'refs/heads/main' # Only run this job if the branch is 'main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: change Directory
        run: |
          cd go-k8s
